### ISSUE TITLE
Experimental :fast-refresh feature is broken

### ISSUE THREAD

**Issue by khmelevskii** [Lokeh/helix#29]
This feature was broken in this commit https://github.com/Lokeh/helix/commit/0ac5b184e65e33407d5de74ec64e36c13c401025

**Comment by Lokeh** [comment]
In the future, please report what you mean by "broken." e.g. if it doesn't reload at all, or throws an error, etc.

That was fixed in https://github.com/Lokeh/helix/commit/7edfe88172a014e8137399cc4bdc42ac134ff92e. I'll prepare a new release soon, but in the meantime you can depend directly on that commit using deps.edn.

FWIW, the fast refresh support is still very experimental and does not work in all cases: edits to namespaces which components transitively dependent on will not trigger a proper refresh.

**Comment by khmelevskii** [comment]
@Lokeh sure.
but unfortunately fast refresh doesn't work for me. I tried to use last commit and it didn't help.
About "broken" - I mean that I can't see any exceptions but refresh doesn't work.
So, this feature works correctly in this commit https://github.com/Lokeh/helix/commit/e43b5ed796a0f8c19539d3b69c05061bf21cfffd and doesn't work after it (tried to use last commit too).

**Comment by Lokeh** [comment]
Ah, I think another change I made is biting you. Apologies for the out of date documentation.

In order to enable fast refresh, you must also create a function to inject the global React devtools hooks, and an after-load hook that will call `helix.experimental.refresh/refresh!`.

An example would be:

```clojure
(ns my-app.dev
  (:require [helix.experimental.refresh :as refresh])

(refresh/inject-hook!)

(defn ^:dev/after-load after-load []
  (refresh/refresh!))
```

And include this in your app at dev time. With shadow-cljs, adding it to your preloads should work.

Let me know if this does or does not fix it for you. Thanks!

**Comment by aiba** [comment]
Looks like `refresh/inject-hook!` was introduced after the latest release (0.0.8).  Can we cut a new release?  (Alternatively, is there is a way for shadow-cljs to depend on a git repo/commit, the way you can with deps.edn?)

**Comment by Lokeh** [comment]
You can use dep.edn with shadow-CLJS as laid out in their user guide.

I will cut a new release tomorrow.

**Comment by khmelevskii** [comment]
@Lokeh thank you! `inject-hook!` works correct. Only one thing, as I can see `helix.experimental.refresh` includes to production build but it would be great to remove this code on prod.

**Comment by aiba** [comment]
> You can use dep.edn with shadow-CLJS as laid out in their user guide.

Oh wow, thanks for pointing this out!

Using that, I got fast-refresh working with react-native.  I realized you actually want to tell react-native to "Disable Fast Refresh" in the simulator.  Otherwise, it tries to do its own fast-refresh hooking which does not jive with shadow-cljs recompile/reload cycles.

Anyway, here's a working example project for anyone interested: https://github.com/aiba/helix-react-native.

I'm really excited to port all my hx code to helix and to be able to use fast-refresh!

**Comment by Lokeh** [comment]
> @Lokeh thank you! `inject-hook!` works correct. Only one thing, as I can see `helix.experimental.refresh` includes to production build but it would be great to remove this code on prod.

Yes, you should configure your project to only include this code in development - either by adding it to `user.cljs` or by adding it to a namespace that is loaded via `:preloads`.

**Comment by khmelevskii** [comment]
@Lokeh thank you. Everything works great!
