### ISSUE TITLE
Sanity check on using hx for hiccup from helix

### ISSUE THREAD

**Issue by aiba** [Lokeh/helix#34]
I couldn't get either sablono or hicada to work with React Native elements, and I always had good success with `hx`, so I've been using this defnc macro:

```clojure
(defmacro defnc [type params & body]
  (let [default-opts {:helix/features {:fast-refresh true}}
        [opts body] (if (map? (first body))
                      [(first body) (rest body)]
                      [{} body])]
    `(helix.core/defnc ~type ~params
       ~(merge default-opts opts)
       (hx.react/f (do ~@body)))))
```

Just wanted a sanity check that `hx.react/f` is the right way to wrap hiccup bodies.

I could also create a PR adding a note to [docs/react-native](../blob/master/docs/react-native.md) that this seems to be the best way to get hiccup working for helix + react-native.

**Comment by Lokeh** [comment]
yeah, using `hx/f` is the best way!

I think it will be difficult to use sablono and hicada in a custom `defnc` macro since they try and parse at compile time, which means it needs to inspect all of the `let`s that are often used in helix component bodies. Using their `html` macros explicitly in each component is probably the best option for now.

Libraries that do fast runtime interpretation (hx, reagent) can easily be wrapped in a custom macro like you have here!
